### ISSUE TITLE
QueryPages

### ISSUE THREAD

**Issue by Lugiia** [mrklintscher/YoutubeSearch#16]
This is not necessarily an issue, it's more of a question if anything.

I saw that you can also search with an amount of pages, however, I haven't found out what the pages even do, or how to call them. How exactly do they work?

**Comment by Mayerch1** [comment]
The `int querypages` are basically, what the pages on the youtube website-search used to be, before google removed them.
If you use `2` as argument, the method will return the results of the first two pages, which represents 40 entries in this case.

Every page is equivalent to an addition of 20 results, as long as you don't hit the limitation for public requests.

**Comment by Lugiia** [comment]
Alright, thank you.

**Comment by radiolondra** [comment]
I want to use pagination in my sample YT search app (with NEXT/PREVIOUS page buttons). But in VideoSearch.cs you used a loop with querypages, so that if I call GetVideos with querypages=4  I'll get the first 4 pages instead to get the fourth page only.
I changed the function a bit and now it works fine with pagination. And obviously it's more fast.

`string content = await Web.getContentFromUrl("https://www.youtube.com/results?search_query=" + querystring + "&page=" + querypages);`

and remove the `for (int i = 1; i <= querypages; i++)` loop.
